name: Bump

on:
  workflow_dispatch:
    inputs:
      monorepo-root:
        description: "Root directory of the monorepo"
        required: true
        default: "./src"
      name:
        description: "Name of the package to bump"
        required: true
        default: "chalk"
      version:
        description: "Version to bump to"
        required: false
        default: "5.2.0"
      create-pr:
        description: "Your sonarqube server host URL"
        required: false
        default: "true"
      base-branch:
        description: "Base branch to create PR against"
        required: false
        default: "main"

defaults:
  run:
    working-directory: "./"

jobs:
  bump-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Bump
        uses: ./
        with:
          monorepo-root: ${{ inputs.monorepo-root }}
          name: ${{ inputs.name }}
          version: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          create-pr: ${{ inputs.create-pr }}
          base-branch: ${{ inputs.base-branch }}
